name: test
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello"
      - name: print bye
        run: echo "bye"
      - name: Version POM's
        shell: powershell
        run: |
           $GitHash = "${{ github.sha }}"
           $ShortGitHash = $GitHash.substring(0,7)
           $ProductVersion = "${{ github.run_number }}"
          
          
    
