name: test
on: workflow_dispatch
env:
  BUILD_NUMBER: "1.0.0.${{ github.run_number }}.${{ github.sha }}"
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello"
      - name: print bye
        run: echo "bye"
      - name: Version POM's
        shell: pwsh
        run: |
           $GitHash = "${{ github.sha }}"
           $ShortGitHash = $GitHash.substring(0,7)
           $ProductVersion = "${{ github.run_number }}"
           $ShortProductVersion = "1.0.0.${{ github.run_number }}.${{ github.sha }}" -replace $GitHash, $ShortGitHash
           echo $ShortProductVersion
           echo $GitHash
           echo $ShortGitHash
