name: test
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello"
      - name: print bye
        run: echo "bye"
      - name: Version POM's
        shell: pwsh
        run: |
           $GitHash = "${{ github.sha }}"
           $ShortGitHash = $GitHash.substring(0,7)
           $ProductVersion = "${{ github.run_number }}"
           $ShortProductVersion = $buildNumber -replace $GitHash, $ShortGitHash
           echo "BUILD_NUMBER=$ShortProductVersion" >> $env:$GITHUB_ENV
           echo $env:BUILD_NUMBER
           
           
